### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pdoconnell** [drewrm/splunk-golang#1]
What license is this issued under? Was it based on the original Splunk sdk and thus [apache](http://www.apache.org/licenses/LICENSE-2.0) licensed?

**Comment by drewrm** [comment]
As you can see, I haven't touched it in ages, and probably won't continue with it since I no longer work with Splunk as much and this was more a learning experience with Go.

Consider it apache license. I'll update to include it but I won't be maintaining this at all.
